apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
      profile: fargate
  template:
    metadata:
      labels:
        app: nginx
        profile: fargate
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev  # ← Match the Deployment's namespace
  labels:
    app: nginx
    profile: fargate  # ← Ensure it matches your Fargate profile
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    profile: fargate  # ← Must match the pod labels to target the correct pods
  type: LoadBalancer
