---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      # The 'profile: fargate' label has been removed.
  template:
    metadata:
      labels:
        app: nginx
        # The 'profile: fargate' label has been removed.
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
    # The 'profile: fargate' label has been removed.
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    # The 'profile: fargate' label has been removed.
  type: LoadBalancer
